### ISSUE TITLE
JuliaIO ownership

### ISSUE THREAD

**Issue by rsrock** [JuliaIO/QuartzImageIO.jl#11]
@timholy, could you make me an owner on JuliaIO?  I'm currently a `member`.  I currently can't control some settings for this repo, such as the tag line that appears at the top.  I assume that making me an owner will fix this.

I think the setting lies here: https://github.com/orgs/JuliaIO/people

Thanks!

**Comment by SimonDanisch** [comment]
You're owner now :)

**Comment by rsrock** [comment]
Many thanks, @SimonDanisch!
