### ISSUE TITLE
Streams: don't always convert to RGBA

### ISSUE THREAD

**Issue by timholy** [JuliaIO/QuartzImageIO.jl#18]
At a minimum, it seems to make sense to pick RGB for non-transparent and RGBA for transparent.

When this is fixed, a3aabb8501a33455bd3da356bcee0665e9b3ad1d should be reverted.

**Comment by rsrock** [comment]
I believe this is fixed in 4c19585.  At least, the test is back to where it was.  Stream handling is still a kluge though.

**Comment by timholy** [comment]
Quite the bug closing festival! Thanks for all your efforts.

**Comment by rsrock** [comment]
Thanks for the new Images!  I'm really liking the new setup.

**Comment by bjarthur** [comment]
i'm enjoying the new Images too!  thanks for all the nice work tim!!
