### ISSUE TITLE
Column first or Row first?

### ISSUE THREAD

**Issue by Evizero** [JuliaIO/QuartzImageIO.jl#31]
for the past few days I was working with `ImageMagick.jl` on my MacBook, but just yesterday I decided to try `QuartzImageIO.jl` again. While it works for me on master (but with Julia 0.5), I do get the Image in a different dimension order than I got it with image magick. 

```julia
julia> img = testimage("lighthouse") # with ImageMagick.jl
512×768 Array{RGB4{N0f8},2}:
[...]

julia> img = testimage("lighthouse") # with QuartzImageIO.jl
768×512 Array{RGB4{N0f8},2}:
[...]
```

Is this a bug or a feature? I thought the idea was to go with the julia array layout unless Axis Arrays are used.

EDIT: maybe related to https://github.com/JuliaIO/QuartzImageIO.jl/blob/master/src/QuartzImageIO.jl#L119-L120 ?

**Comment by timholy** [comment]
Even with AxisArrays, in future visualization tools it will be julia array layout unless you pass in explicit instructions to the contrary. I don't plan on having special behavior for axes named `:x` and `:y`.

**Comment by kmsquire** [comment]
I just ran into this while testing https://github.com/kmsquire/VideoIO.jl/pull/92.  

Interestingly, in IJulia/Jupyter, an image read using QuartzImageIO (with the wrong axis order) displays properly, but an image read from a video file (with the correct axis order) displays transposed.  

So I'm wondering if the order in QuartzImageIO was changed so it displayed properly, when in fact the change needed to occur in IJulia?

(Cc: @rsrock (who probably doesn't need to be cc'd))

**Comment by timholy** [comment]
I think the orientation in ImageView is correct now, and so can be used as a reference (worth double-checking, of course). That bypasses all the I/O packages except VideoIO, which might help us avoid a scary who-do-you-trust problem.

Fundamentally, the ultimate test is: a 20-by-200 video should be short and wide.

**Comment by SimonDanisch** [comment]
I have observed images being flipped in QuartzImageIO compared to ImageMagick ;)

**Comment by rsrock** [comment]
IIRC, orientation used to be handled through the `imageprops` dict, but that's now been removed. I'll have to stick a `permutedims` in to handle the new way of doing things. 

IJulia probably works just fine, because the image is flipped once when it is read, and once again when it is written to the stream for viewing.

I will check against ImageView, since it seems to be the gold standard.

**Comment by SimonDanisch** [comment]
How do you get the orientation?

**Comment by rsrock** [comment]
Currently, we don't.  We should probably get the image orientation from the Exif data, and if that doesn't exist, use a (y, x) order.  Sound about right?

**Comment by timholy** [comment]
Yes. BTW, ImageMagick.jl now reads Exif data if present; there's even a test, if you'd find that useful.

**Comment by rsrock** [comment]
The rsr/orientation branch has a quick fix, which just defaults to row-major ordering.

**Comment by rdeits** [comment]
I just ran into this and was utterly baffled by it until I found this issue. The `rsr/orientation` branch does resolve the issue for me. Thank you!

**Comment by SimonDanisch** [comment]
should we merge it? I think defaulting to row-major is what should be done nowadays, no? We can try to do it lazily whenever someone has time to deal with it! ;)

**Comment by timholy** [comment]
Lazy isn't hard, just change `permutedims` to `permuteddimsview`. But the result won't be as cache efficient for most julia operations, so unless the image is really big I think it's better to do it eagerly.

**Comment by rsrock** [comment]
Eager it is.  Will merge a fix soon and tag a new version, once the tests pass.
