### ISSUE TITLE
(When trying to load TIFF files): WARNING: QuartzImageIO created no image source

### ISSUE THREAD

**Issue by tomerarnon** [JuliaIO/QuartzImageIO.jl#34]
I recently installed QuartzImageIO and now get the warning message above when trying to load .tiff images. The problem does not occur for JPGs or PNGs.

i.e.

>  using Images
> 
> load("image.tiff")
> or
> Images.load("images.tiff")

 wont return a value and will give the warning: WARNING: QuartzImageIO created no image source

> data(load("image.tiff")

returns:

> MethodError: no method matching data(::Void)
> Closest candidates are:
>   data(!Matched::ImageMetadata.ImageMeta{T,N,A<:AbstractArray}) at /Users/tomer/.julia/v0.5/ImageMetadata/src/ImageMetadata.jl:198
>   data(!Matched::AbstractArray{T,N}) at /Users/tomer/.julia/v0.5/ImageCore/src/deprecated.jl:88
>  in include_string(::String, ::String) at loading.jl:441
>  in include_string(::String, ::String, ::Int64) at eval.jl:28
>  in include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N}) at eval.jl:32
>  in (::Atom.##53#56{String,Int64,String})() at eval.jl:40
>  in withpath(::Atom.##53#56{String,Int64,String}, ::String) at utils.jl:30
>  in withpath(::Function, ::String) at eval.jl:46
>  in macro expansion at eval.jl:57 [inlined]
>  in (::Atom.##52#55{Dict{String,Any}})() at task.jl:60
>

**Comment by rsrock** [comment]
That's what you'll see if the file `image.tiff` doesn't exist.  Check for `.tif` vs. `.tiff` ( I get caught by this all the time).

Also, see if you have the image in your working directory.  Type `;` to get the `shell>` prompt, followed by `ls` (or perhaps `dir` on Windows).

**Comment by tomerarnon** [comment]
Thanks for the response. 
However, this doesn't seem to be the problem. The file is named .tiff and not .tif, and I am actually specifying it by its full path in the code. `/Users/tomer/ ... /image.tiff` on Mac.
I've just triple checked the path and it is correct.

**Comment by rsrock** [comment]
Can you open the file with Preview.app?  If you can, would you be able to share the file?  There's probably something unusual with it.

**Comment by tomerarnon** [comment]
Your response brought up a very interesting issue, since so far I have only been trying to open the one `.tiff` file. To answer your question:  I can open it in preview just fine.
But it seems another file, `.tif` this time in case that is the difference, _is_ working with `Images.load("image2.tif")` so perhaps you're right that there's something strange about the file (not that I know what that could be)

Trying to attach the images, I get 

> "We don't support that file type."

Is there some other way to share the images? (new to Github)

**Comment by tomerarnon** [comment]
I stuck the image in question in the repository "hello-world" for simplicity.
[https://github.com/tomerarnon/hello-world](url)

**Comment by rsrock** [comment]
Strange, looking at the first few bytes of this file, it appears to be a .png, not a .tiff.  Did you produce it yourself?

It also appears to be an indexed color image.  Unfortunately, we don't have that capability in QuartzImageIO yet.  However, you should be able to open this if you use ImageMagick.jl, I believe.

**Comment by tomerarnon** [comment]
I didn't produce it myself, and that is quite strange indeed.
It also appears to load correctly if I run the same commands in Windows rather than Mac OS (i.e not using QuartzImageIO).
I'll try to run it again on the Mac using ImageMagick.

**Comment by tomerarnon** [comment]
Thanks for your help!
ImageMagick loaded the image successfully.
