### ISSUE TITLE
save_ should use mapped image, not original, to detect element type

### ISSUE THREAD

**Issue by rdeits** [JuliaIO/QuartzImageIO.jl#37]
I think that `img` here: https://github.com/JuliaIO/QuartzImageIO.jl/blob/efb89816fe1a99fbcf413b94a5fc6710108eddb0/src/QuartzImageIO.jl#L237 should actually be `imgm`. That is, I think `save_()` should be getting the element type of the result of `mapCG`, not the original input image. But I'm not familiar with the inner workings of this package, so I may be wrong. 

This came up while working on https://github.com/JuliaImages/Images.jl/issues/624 To see the issue, try this:

```julia
julia> using Colors, FixedPointNumbers, FileIO, QuartzImageIO

julia> QuartzImageIO.save_(Stream(format"PNG", IOBuffer()), zeros(HSV{Float32}, 1, 1))
ERROR: QuartzImageIO: tried to save unknown buffer type ColorTypes.HSV{Float32}
 in #save_#8(::Bool, ::ImageCore.#clamp01nan, ::Function, ::FileIO.File{FileIO.DataFormat{:PNG}}, ::Array{ColorTypes.HSV{Float32},2}) at /Users/rdeits/.julia/v0.5/QuartzImageIO/src/QuartzImageIO.jl:250
 in (::QuartzImageIO.#kw##save_)(::Array{Any,1}, ::QuartzImageIO.#save_, ::FileIO.File{FileIO.DataFormat{:PNG}}, ::Array{ColorTypes.HSV{Float32},2}) at ./<missing>:0
 in #save#5(::Array{Any,1}, ::Function, ::FileIO.File{FileIO.DataFormat{:PNG}}, ::Array{ColorTypes.HSV{Float32},2}, ::Vararg{Array{ColorTypes.HSV{Float32},2},N}) at /Users/rdeits/.julia/v0.5/QuartzImageIO/src/QuartzImageIO.jl:20
 in (::QuartzImageIO.#kw##save)(::Array{Any,1}, ::QuartzImageIO.#save, ::FileIO.File{FileIO.DataFormat{:PNG}}, ::Array{ColorTypes.HSV{Float32},2}, ::Vararg{Array{ColorTypes.HSV{Float32},2},N}) at ./<missing>:0
 in getblob at /Users/rdeits/.julia/v0.5/QuartzImageIO/src/QuartzImageIO.jl:313 [inlined]
 in #save_#11 at /Users/rdeits/.julia/v0.5/QuartzImageIO/src/QuartzImageIO.jl:304 [inlined]
 in save_(::FileIO.Stream{FileIO.DataFormat{:PNG},Base.AbstractIOBuffer{Array{UInt8,1}}}, ::Array{ColorTypes.HSV{Float32},2}) at /Users/rdeits/.julia/v0.5/QuartzImageIO/src/QuartzImageIO.jl:304
```

Replacing `img` with `imgm` avoids that error.

**Comment by rdeits** [comment]
Interestingly, actually making the suggested change breaks the tests, specifically:

```
Earth Apollo: Test Failed
  Expression: eltype(oimg) == eltype(img)
   Evaluated: ColorTypes.RGBA{FixedPointNumbers.Normed{UInt8,8}} == ColorTypes.RGB4{FixedPointNumbers.Normed{UInt8,8}}
Stacktrace:
 [1] macro expansion at /Users/rdeits/.julia/v0.6/QuartzImageIO/test/runtests.jl:62 [inlined]
 [2] macro expansion at ./test.jl:853 [inlined]
 [3] macro expansion at /Users/rdeits/.julia/v0.6/QuartzImageIO/test/runtests.jl:0 [inlined]
 [4] macro expansion at ./test.jl:853 [inlined]
 [5] anonymous at ./<missing>:?
Earth Apollo: Test Failed
  Expression: oimg == img
```

**Comment by rsrock** [comment]
Thanks for reporting this.  The actual fix lies elsewhere, due to the strange way the CoreGraphics libraries handle pixel values.  If I understand correctly, the output buffer has to have 4 components, even if the last one isn't used. So to distinguish RGB4 (or RGV, or HSV) images from RGBA images, we have to peek at the source image.

I just pushed a change that should handle this case for you.  You can `Pkg.checkout("QuartzImageIO")` to try it out, until I tag a new version in the next few days.

**Comment by rdeits** [comment]
My original problem is indeed fixed on master. Thanks!!

**Comment by timholy** [comment]
Looks like this needs a tag to fix Travis failures for Images.jl (e.g., https://github.com/JuliaImages/Images.jl/pull/643).

**Comment by rsrock** [comment]
Thanks for the reminder, just tagged a new release.
