### ISSUE TITLE
Silent failure related to missing ufixedtype

### ISSUE THREAD

**Issue by rsrock** [JuliaIO/QuartzImageIO.jl#4]
In getting the tests working, I hit an error with the first TestImages file, "Autumn Leaves".  The error turned out to be a missing `ufixedtype` dict, which I assume migrated over to ImageMagick.  No worries, I just put it in here.

The weird thing was the failure mode.  `FileIO` would actually drop down into ImageMagick on its own.  Println testing got me to this line, with the missing `Images.ufixedtype`: https://github.com/JuliaIO/QuartzImageIO.jl/blob/d459f06b05c46edd893532c82fbfcfbfea96fe92/src/QuartzImageIO.jl#L89

Before 5729663, this line would run, then silently return from that function (leading to ImageMagick taking over, and luckily ImageMagick has a different idea of byte ordering, otherwise I wouldn't have even noticed!).  A println() on the next line did not run.

I find this weird, how is it that the missing `Images.ufixedtype` didn't give me some sort of an error?  @timholy @SimonDanisch

**Comment by SimonDanisch** [comment]
I'm close to going to bed, so I'm not sure if I'm understanding this correctly.
But isn't that exactly because of our current error handling and the try catch in save/load as I pointed out?!
`FileIO` is supposed to drop down to `ImageMagick` on its own if there is any error in `QuartzImageIO`. It does it silently at the moment, which is not perfect.

**Comment by rsrock** [comment]
Ah, that's the part that I didn't get, that there's now a `try/catch` block in there in the save/load code.  It used to be that image readers would just return "nothing" if they failed, and the reader would hand off to the next reader in the chain (usually ImageMagick).  We'll have to lock down that `try/catch` with a specific error type. 

I'm sure that's it.

**Comment by rsrock** [comment]
Fixed in FileIO v0.0.3
