### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by rsrock** [JuliaIO/QuartzImageIO.jl#42]
See JuliaImages/Images.jl#640

**Comment by timholy** [comment]
For a fix, ref https://github.com/JuliaIO/ImageMagick.jl/blob/dbf13674109451c44ba30f4962bf9c825410943b/src/ImageMagick.jl#L228-L238. `Compat.collect` always returns an `Array`.

**Comment by rsrock** [comment]
Seems to work now
