### ISSUE TITLE
Naming bikeshed

### ISSUE THREAD

**Issue by rsrock** [JuliaIO/QuartzImageIO.jl#5]
I hate to bring this up, but I'm not sure `QuartzImageIO` is the best name for this.  Quartz refers to the drawing layer, if I understand correctly.  Most of actual Image IO library functions used here come from CoreGraphics (which is a mouthful, admittedly)

Naming here is a bit of a mess, actually.  See the discussion here: http://stackoverflow.com/questions/1877987/whats-the-difference-between-quartz-core-core-graphics-and-quartz-2d

I'm not overly fond of `OSXnative`.  That was a fine name when it was buried three layers down in `Images`, but not so good for public consumption.  But should OS X be part of the name?  Or Mac?

`OSXImageIO`
`MacImageIO`  -- I think I like this one, at the moment.

In any event, it might be best to settle this quickly, before anyone discovers this package :smile:

**Comment by timholy** [comment]
I don't have strong feelings. Original bikeshed happened [here](https://github.com/JuliaLang/METADATA.jl/pull/3544), perhaps it would be good to just add to that issue.

**Comment by rsrock** [comment]
I think we should come to a decision on this before tagging a new Images, because by then the horse will have left the stable...  I'll jump over there.

**Comment by timholy** [comment]
I'll try to wait to tag a new release until this is resolved.
