### ISSUE TITLE
RGBX not defined

### ISSUE THREAD

**Issue by jakewilliami** [JuliaIO/QuartzImageIO.jl#68]
Trying to load QuartzImageIO does not seem to work: I get an error saying `RGBX not defined` (see below).  After I ran what is depicted below, I tried adding and using `Colors` and `ColorTypes`, but I am getting the same error.  As per the readme, I have also tried just using `FileIO` and loading a `jpg`, but cannot get this working (same error).

```
pkg> status
Status `~/FaceDetection.jl/Project.toml`
  [336ed68f] CSV v0.7.7
  [a93c6f00] DataFrames v0.21.7
  [5789e2e9] FileIO v1.4.3
  [c91e804a] Gadfly v1.3.0
  [09f84164] HypothesisTests v0.10.0
  [4381153b] ImageDraw v0.2.3
  [82e4d734] ImageIO v0.3.0
  [6218d12a] ImageMagick v1.1.6
  [86fae568] ImageView v0.10.9
  [916415d5] Images v0.22.2
  [f09324ee] Netpbm v0.4.0
  [91a5bcdd] Plots v1.0.14
  [92933f4c] ProgressMeter v1.3.1
  [dca85d43] QuartzImageIO v0.7.3
  [f3b207a7] StatsPlots v0.14.11
  [8ba89e20] Distributed
  [de0858da] Printf
  [8dfed614] Test

julia> using Images, FileIO, QuartzImageIO
[ Info: Precompiling QuartzImageIO [dca85d43-d64c-5e67-8c65-017450d5d020]
ERROR: LoadError: UndefVarError: RGBX not defined
Stacktrace:
 [1] top-level scope at /Users/jakeireland/.julia/packages/QuartzImageIO/hnNSo/src/QuartzImageIO.jl:354
 [2] include(::Function, ::Module, ::String) at ./Base.jl:380
 [3] include(::Module, ::String) at ./Base.jl:368
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:331 [inlined]
 [6] eval(::Expr) at ./client.jl:467
 [7] top-level scope at ./none:3
in expression starting at /Users/jakeireland/.julia/packages/QuartzImageIO/hnNSo/src/QuartzImageIO.jl:354
ERROR: Failed to precompile QuartzImageIO [dca85d43-d64c-5e67-8c65-017450d5d020] to /Users/jakeireland/.julia/compiled/v1.5/QuartzImageIO/n8vDP_S0ZaK.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1290
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923
```

**Comment by jakewilliami** [comment]
Tested on Arch Linux and is working fine.  I am using a MBP, running Mojave (10.14.6).  Both machines are using Julia 1.5.1.

**Comment by johnnychen94** [comment]
should be fixed by https://github.com/JuliaIO/Netpbm.jl/pull/21

**Comment by johnnychen94** [comment]
could also be fixed by #69

**Comment by jakewilliami** [comment]
Thanks for identifying the problem @jonnychen94.  Do I need to wait for the pr to be merged into Netpbm, and then run `pkg> update`?

**Comment by johnnychen94** [comment]
Whichever PR merged and tagged for a release, an `pkg> update` would get you back on track.

**Comment by timholy** [comment]
@jakewilliami, https://github.com/JuliaRegistries/General/pull/21160 should auto-merge in 15 minutes and you'll be set.

@johnnychen94, if you think #69 is desirable even with the Netpbm update, I have no objections.

**Comment by johnnychen94** [comment]
Since we delegate the ColorTypes version resolving to ImageCore, and since ImageCore 0.8 declares compatibility for ColorTypes 0.8 and 0.9. For example, ImageCore 0.8 declares compatibility to Colors v0.11, which again declares compatibility to ColorTypes 0.9

We don't know if there are other packages like Netpbm that locks to the old versions and it would be better to get #69 in as preparation. Since it get fixed by a new Netpbm version, we could ship #69 with potential new PRs in the future.

**Comment by johnnychen94** [comment]
> JuliaRegistries/General#21160 should auto-merge in 15 minutes and you'll be set.

Heads up to the General synchronization issue https://github.com/JuliaRegistries/General/issues/16777 since Julia 1.5 uses PkgServer by default. The delay could occasionally be hours.

**Comment by jakewilliami** [comment]
> The delay could occasionally be hours.

Good to know, thanks @johnnychen94.  No rush in my case :)
