### ISSUE TITLE
The "O" part

### ISSUE THREAD

**Issue by rsrock** [JuliaIO/QuartzImageIO.jl#7]
File output has been on my todo list for quite a while.

Available output formats are:

```
(
    "public.jpeg",
    "public.png",
    "com.compuserve.gif",
    "public.jpeg-2000",
    "public.tiff",
    "com.apple.icns",
    "com.adobe.photoshop-image",
    "com.adobe.pdf",
    "com.microsoft.ico",
    "com.microsoft.bmp",
    "com.truevision.tga-image",
    "com.sgi.sgi-image",
    "com.ilm.openexr-image",
    "public.pbm",
    "public.pvr",
    "com.apple.rjpeg"
)
```

**Comment by cstjean** [comment]
@rsrock I'm getting issues with ImageMagick, and Tim suggested that I look into supporting output in QuartzImageIO instead. It doesn't look too hard. Did you want to do it yourself, or can I go ahead with it?

**Comment by rsrock** [comment]
By all means, take a stab at it.  I have some time now to work on Julia again, so I can give you some pointers if you run into issues.  Let me know how it goes.

On Nov 18, 2015, at 10:57 AM, cstjean <notifications@github.com<mailto:notifications@github.com>> wrote:


@rsrock<https://github.com/rsrock> I'm getting issues with ImageMagick, and Tim suggested that I look into supporting output in QuartzImageIO instead. It doesn't look too hard. Did you want to do it yourself, or can I go ahead with it?

—
Reply to this email directly or view it on GitHub<https://github.com/JuliaIO/QuartzImageIO.jl/issues/7#issuecomment-157777679>.

-------------------------------------------------------------------
Ronald S. Rock, Jr., Associate Professor
Dept. of Biochemistry and Molecular Biology, The University of Chicago
GCIS W240, 929 E. 57th St.
Chicago, IL 60637   USA
+1 773.702.0716 (w), +1 773.702.0439 (f)
rrock@uchicago.edu<mailto:rrock@uchicago.edu>

**Comment by cstjean** [comment]
It went pretty well, although Apple's docs were pretty disappointing. I can now output arbitrary image types with alpha-channel, but the first step is `convert(Image{RGBA{UFixed8}}, img)`. @timholy Is that a deal-breaker? Obviously, I can write code to deal with every image type combination, but that would take some time.

**Comment by rsrock** [comment]
It's a good start.  I imagine that the most common use at first will be for IJulia, and that convert step should be fine.

Arbitrary formats can come later.

Would you like to make a pull request?

**Comment by timholy** [comment]
Not a dealbreaker, especially in a package that's for a specific platform that I don't have to maintain myself :smile:. Nice work!

**Comment by rsrock** [comment]
Knock it off over there :wink:

**Comment by rsrock** [comment]
Close by #12.
